[build]
builder = "nixpacks"

[build.nixpacks]
pkgs = ["nodejs_22"]

[deploy]
startCommand = "node apps/backend/dist/src/main.js"

[[services]]
name = "backend"
buildCommand = "cd apps/backend && npm install && npm run build"
startCommand = "node apps/backend/dist/src/main.js"
